### ISSUE TITLE
[troubleshooting] iFrame UserScript

### ISSUE THREAD

**Issue by dnmTX** [emCupid/adg_cn#1]
@emCupid i'm moving here for the time being until we smooth things out with the script cause we were in the wrong repo and i don't think the AdGuard team was very pleased with what we were doing there. I very much hope that it's OK with you.
This is what i've noticed on certain websites in console log:
![CaptureDOM](https://user-images.githubusercontent.com/34774426/122348683-075f1e80-cf11-11eb-8533-1acb1ba5f5bb.PNG)

Do you think you can suppress those messages. Make the observer to monitor only iframe related changes?
This is it for now,i'm still vigorously testing on my end though 😉 
Cheers  欢呼和掌声 👍

**Comment by dnmTX** [comment]
@emCupid another thing i would like help with.
It's regarding google's recaptcha. 
There are websites that recaptcha is present(box that you have to click on pictures and all that) and there are some that it's just placed as a iframe(sucking up memory only) and can be easily removed without braking anything.
Can you script something and i'll manually input those websites to make it not to ignore google's iframe?

P.S. @emCupid just to clarify,if i'm too annoying and/or you don't have the desire to help,just say it.
I'll close this here,promise to never bother you again.

**Comment by emCupid** [comment]
Userscript Header have match and exclude
so that's easy

**Comment by dnmTX** [comment]
Sure but when you have `@match  *://*/*` it's like globaly applied,and then you have this:
`isrc = /google.com|youtube.com|youtube-nocookie.com....` which is part of the script and it doesn't listen to neither 
`@match` or `@include`. I tried.

**Comment by dnmTX** [comment]
Maybe something like another `isrc = .....` and then another `if (isrc.test(element.src))` this time without the exlamation point....
What do you think?
Just to clarify,again,the point here is on certain websites to delete google's iframe. Right now is set to no to on all websites.

**Comment by emCupid** [comment]
@match *://*.github.com/*
@match *://*.xxxxx.com/ex/*
......

**Comment by dnmTX** [comment]
It doesn't work,because the actual script is not deleting it because you have this: `isrc = /google.com..` in it.
As you know,the script is set up to ignore(not delete) certain iframes like google,youtube....Now how can we do NOT TO IGNORE IT(and delete it) on only certain websites?
It's just for google's stupid recaptcha iframe.

**Comment by emCupid** [comment]
```
@match : //.github.com/*
@match : //.xxxxx.com/ex/*
if (isrc.test(element.src)) {
            ...
}
```

**Comment by dnmTX** [comment]
```
@match : //.github.com/*
@match : //.xxxxx.com/ex/*
if (isrc.test(element.src)) {
            ...
}
```
That;s just doesn't make sence at all.
That's ok. I do appreciate your initial help but obviously you're not interested helping smooth things out.
I'll figure it out on my own...eventually. No bad feelings here(i'm greatfull),you're just,hard to work with.
Cheers.

**Comment by emCupid** [comment]
If you want to write with the original script, there must be a function to get the main domain name of the current website. This will be troublesome, so we use @ match to match the URL we want to run, and create a new script to solve it.

**Comment by emCupid** [comment]
and my English is not very well,most of the time I don't know how to express

**Comment by dnmTX** [comment]
OK....let's say i want to do that in youtube.com(for example) and i have the script set to ignore any frame with `src=` youtube right?
So can't i just place on the TOP:
```
src = /youtube.com/i;
function reCaptcha() { document.querySelectorAll('iframe').forEach(function(element) {
        if (isrc.test(element.src)) {
            console.log('Iframe Killa - Removing Element:', element);
            element.parentNode.removeChild(element);
        }
    })
}
```
And then continue with the initial script.Logically thinking here,as this part ☝️  is ON THE TOP it will allways execute first,this way even if the rest of the script is set to ignore any youtube iframe it would not matter because it will be delete already.
Correct me if i'm wrong here,i just don't see point to make another script.

**Comment by dnmTX** [comment]
Never mind,i see what you mean. In that scenario i would not be able to exclude websites in which recaptcha is needed.
Eh...well.....

**Comment by emCupid** [comment]
I'm a little confused, em......
I still don't quite understand your point

**Comment by dnmTX** [comment]
> I'm a little confused, em......
I still don't quite understand your point

That's OK,what is important here is that i got your point and i see that i'm just asking for something that can not happen.

Next question(hoping that at least this will be possible):
For a moment forget about what we disscussed here so far. So imagine my script,and on the part:
`isrc = /google.com|youtube.com|....`  can i use some **regex** and this is strictly about google?
So instead of `isrc = /google.com|` to be `isrc = /google.com/recaptcha/*|youtube.com....`
Do you think it will work like this?
This way i at least will leave the recaptcha only and everything else with google on it will be removed.
Tell me it could work...please 🤔

**Comment by emCupid** [comment]
yes.but it is RegExp,so It can't be used directly *,
and "/" must be escaped
e.g.
```
isrc = /google.com\/iframe\/.*recaptcha|\/aaaa\/bbbb.html.*ccccc/i
```

**Comment by dnmTX** [comment]
I see,this is usually the whole iframe link:
`https://www.google.com/recaptcha/api2/anchor?ar=1&k=6LfDWNsUAAAAAGaxIiiQpfv-5_b8zWR4mgv7RKvs&co=aHR0cHM6Ly9zdHJlYW10YXBlLmNvbTo0NDM.&hl=en&v=FDTCuNjXhn1sV0lk31aK53uB&size=invisible&cb=5kfm8xbivzc3`
So `isrc = /google.com\/recaptcha\/api2\/|youtube.com....` good enough or..?

**Comment by emCupid** [comment]
```
isrc = /google.com\/recaptcha\/api2\/|youtube.com/i
```

**Comment by dnmTX** [comment]
And it will match the recaptcha only links and other links,like,for example:
`src="https://scone-pa.clients6.google.com/static/proxy.html?.......` will be deleted?

**Comment by emCupid** [comment]
> And it will match the recaptcha only links and other links,like,for example:
> `src="https://scone-pa.clients6.google.com/static/proxy.html?.......` will be deleted?

yes

**Comment by emCupid** [comment]
I'm busy recently, so sometimes I can't reply in time.

**Comment by dnmTX** [comment]
@emCupid that's fine,you're big help and we got some progress here with the RegExp.
I reopened the issue here just in case,but i'm sure i will not be bothering you anytime soon. 
There's not much more we can do to improve the script anyway.
Good day to you,i'm off to bed(it's late here) 👍

**Comment by dnmTX** [comment]
@emCupid i did some research and by the look of it `window.location.href` would fetch the current page URL
Can we use that to determine the website that i want the google iframe to be deleted?
It's just a question.

**Comment by dnmTX** [comment]
Oops...one more 😄....anything we can improve on this one? If NO,can you make it `function (....` to be complete. Thank you 👍 
```
var iframes = document.querySelectorAll('iframe');
for (var i = iframes.length; i--;) {
    if (iframes[i].src.match('youtube') !== null && iframes[i].src.match('allow') === null) {
        iframes[i].allowFullscreen = true;
        iframes[i].src = iframes[i].src;
    }
};
```
**Notes**: `document-end`  `@include`  `@grant ?????`
P.S. Reloading the iframe: `iframes[i].src = iframes[i].src;` causing the whole page to reload,annoying as hell. 
Any other methods to refresh iframe?

**Comment by dnmTX** [comment]
@emCupid my friend,gift for you: https://greasyfork.org/en/scripts/428243-don-t-track-me-google/code
He just published it per my request 😉 
If you're using Google to search,that UserScript is a MUST!!!  Enjoy it 👍

**Comment by dnmTX** [comment]
@emCupid i need to exclude `id="videoplayer"` but have the rest deleted. Can we do that?
I only have whitelist for source: `src=` 🤔
